// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp1.DbContexts;

#nullable disable

namespace WpfApp1.Migrations
{
    [DbContext(typeof(SpaceXDbContext))]
    [Migration("20221221214933_AddedLaunchEntityAndAllRelatedStuff")]
    partial class AddedLaunchEntityAndAllRelatedStuff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("WpfApp1.DTOs.LaunchDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LaunchDateUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LaunchSuccess")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Upcoming")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Launches");
                });

            modelBuilder.Entity("WpfApp1.DTOs.RocketDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("EngineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RocketID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RocketName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rockets");
                });

            modelBuilder.Entity("WpfApp1.DTOs.ShipDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearOfBuild")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ships");
                });
#pragma warning restore 612, 618
        }
    }
}
