// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp1.DbContexts;

#nullable disable

namespace WpfApp1.Migrations
{
    [DbContext(typeof(SpaceXDbContext))]
    partial class SpaceXDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("WpfApp1.DTOs.RocketDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("EngineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RocketID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RocketName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rockets");
                });
#pragma warning restore 612, 618
        }
    }
}
